apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: chefathands
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:sqlserver://chef-database-server.database.windows.net:1433;database=chef-at-hands-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30"
  SPRING_DATASOURCE_USERNAME: "Pazinapast153@chef-database-server"
  SPRING_DATASOURCE_PASSWORD: "Medijota23!"